// Small C ABI boundary around AppKit. Returned JSON is malloc-owned; Rust frees it.
#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#include <unistd.h>

static NSString *const InternalType = @"app.clipdeck.internal-write";
static NSPasteboard *board(const char *name) {
    return name ? [NSPasteboard pasteboardWithName:@(name)] : NSPasteboard.generalPasteboard;
}
static char *json(id value) {
    NSData *data = [NSJSONSerialization dataWithJSONObject:value options:0 error:nil];
    if (!data) return NULL;
    char *out = malloc(data.length + 1);
    if (!out) return NULL;
    memcpy(out, data.bytes, data.length);
    out[data.length] = 0;
    return out;
}
void clipmo_free(char *value) { free(value); }

int64_t clipmo_change_count(const char *name) {
    @autoreleasepool { return board(name).changeCount; }
}

char *clipmo_read(const char *name) {
    @autoreleasepool {
        NSPasteboard *pb = board(name);
        NSInteger revision = pb.changeCount;
        // Respect password-manager/history opt-outs before reading any payload.
        NSArray *blocked = @[InternalType, @"org.nspasteboard.ConcealedType",
            @"org.nspasteboard.TransientType", @"org.nspasteboard.AutoGeneratedType",
            @"com.agilebits.onepassword"];
        if ([pb availableTypeFromArray:blocked]) return NULL;
        NSMutableDictionary *result = [NSMutableDictionary dictionary];
        NSArray<NSURL *> *urls = [pb readObjectsForClasses:@[NSURL.class]
            options:@{NSPasteboardURLReadingFileURLsOnlyKey: @YES}];
        NSMutableArray *files = [NSMutableArray array];
        for (NSURL *url in urls) if (url.fileURL && url.path) [files addObject:url.path];
        result[@"files"] = files;
        NSString *text = [pb stringForType:NSPasteboardTypeString];
        if (text) result[@"text"] = text;
        NSString *html = [pb stringForType:NSPasteboardTypeHTML];
        if (html) result[@"html"] = html;
        NSData *rtf = [pb dataForType:NSPasteboardTypeRTF];
        if (rtf) {
            NSString *value = [[NSString alloc] initWithData:rtf encoding:NSUTF8StringEncoding];
            if (value) result[@"rtf"] = value;
        }
        if (!files.count) {
            NSData *png = [pb dataForType:NSPasteboardTypePNG];
            if (!png) {
                NSData *tiff = [pb dataForType:NSPasteboardTypeTIFF];
                if (tiff) png = [[NSBitmapImageRep imageRepWithData:tiff]
                    representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
            }
            if (png) result[@"image"] = [png base64EncodedStringWithOptions:0];
        }
        NSRunningApplication *app = NSWorkspace.sharedWorkspace.frontmostApplication;
        if (app.executableURL.path) result[@"source"] = @{
            @"name": app.localizedName ?: @"Application",
            @"exePath": app.executableURL.path, @"iconPath": NSNull.null};
        // Never combine formats from two clipboard generations.
        if (revision != pb.changeCount) return NULL;
        return json(result);
    }
}

int clipmo_write(const char *name, const char *payload) {
    @autoreleasepool {
        NSData *data = [@(payload) dataUsingEncoding:NSUTF8StringEncoding];
        NSDictionary *value = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
        if (![value isKindOfClass:NSDictionary.class]) return 0;
        NSMutableArray<NSPasteboardItem *> *items = [NSMutableArray array];
        for (NSString *path in value[@"files"]) {
            NSPasteboardItem *item = [NSPasteboardItem new];
            [item setString:[NSURL fileURLWithPath:path].absoluteString forType:NSPasteboardTypeFileURL];
            [items addObject:item];
        }
        if (!items.count) [items addObject:[NSPasteboardItem new]];
        NSPasteboardItem *item = items.firstObject;
        if (value[@"text"]) [item setString:value[@"text"] forType:NSPasteboardTypeString];
        if (value[@"html"]) [item setString:value[@"html"] forType:NSPasteboardTypeHTML];
        if (value[@"rtf"]) [item setData:[value[@"rtf"] dataUsingEncoding:NSUTF8StringEncoding] forType:NSPasteboardTypeRTF];
        if (value[@"image"]) {
            NSData *png = [[NSData alloc] initWithBase64EncodedString:value[@"image"] options:0];
            if (!png) return 0;
            [item setData:png forType:NSPasteboardTypePNG];
        }
        for (NSPasteboardItem *entry in items) [entry setString:@"1" forType:InternalType];
        NSPasteboard *pb = board(name);
        [pb clearContents];
        return [pb writeObjects:items] ? 1 : 0;
    }
}

int clipmo_foreground(void) {
    @autoreleasepool { return NSWorkspace.sharedWorkspace.frontmostApplication.processIdentifier; }
}
int clipmo_accessibility(int prompt) {
    @autoreleasepool {
        return AXIsProcessTrustedWithOptions((__bridge CFDictionaryRef)
            @{(__bridge NSString *)kAXTrustedCheckOptionPrompt: @(prompt != 0)});
    }
}
int clipmo_activate(int pid) {
    @autoreleasepool {
        if (pid <= 0 || pid == getpid()) return 0;
        NSRunningApplication *app = [NSRunningApplication runningApplicationWithProcessIdentifier:pid];
        return app && !app.terminated && [app activateWithOptions:NSApplicationActivateIgnoringOtherApps];
    }
}
int clipmo_paste(int pid) {
    if (pid <= 0 || pid == getpid() || clipmo_foreground() != pid || !clipmo_accessibility(0)) return 0;
    CGEventSourceRef source = CGEventSourceCreate(kCGEventSourceStatePrivate);
    if (!source) return 0;
    CGEventRef down = CGEventCreateKeyboardEvent(source, 9, true); // ANSI V
    CGEventRef up = CGEventCreateKeyboardEvent(source, 9, false);
    if (!down || !up) {
        if (down) CFRelease(down);
        if (up) CFRelease(up);
        CFRelease(source);
        return 0;
    }
    CGEventSetFlags(down, kCGEventFlagMaskCommand);
    CGEventSetFlags(up, kCGEventFlagMaskCommand);
    CGEventPostToPid(pid, down);
    CGEventPostToPid(pid, up);
    CFRelease(down); CFRelease(up); CFRelease(source);
    return 1;
}

static NSDictionary *identity(NSBundle *bundle, NSString *executable, NSString *name) {
    return @{@"id": [@"exe:" stringByAppendingString:executable],
        @"displayName": name ?: executable.lastPathComponent,
        @"executablePath": executable, @"executableName": executable.lastPathComponent};
}
char *clipmo_apps(int installed) {
    @autoreleasepool {
        NSMutableDictionary *apps = [NSMutableDictionary dictionary];
        for (NSRunningApplication *app in NSWorkspace.sharedWorkspace.runningApplications) {
            if (app.activationPolicy != NSApplicationActivationPolicyRegular || !app.executableURL.path) continue;
            NSMutableDictionary *value = [identity([NSBundle bundleWithURL:app.bundleURL], app.executableURL.path, app.localizedName) mutableCopy];
            value[@"running"] = @YES; value[@"installed"] = @(app.bundleURL != nil);
            apps[app.executableURL.path] = value;
        }
        if (installed) {
            NSArray *roots = @[@"/Applications", @"/System/Applications", [NSHomeDirectory() stringByAppendingPathComponent:@"Applications"]];
            for (NSString *root in roots) {
                NSDirectoryEnumerator *walk = [NSFileManager.defaultManager enumeratorAtURL:[NSURL fileURLWithPath:root]
                    includingPropertiesForKeys:nil options:NSDirectoryEnumerationSkipsHiddenFiles | NSDirectoryEnumerationSkipsPackageDescendants errorHandler:nil];
                for (NSURL *url in walk) {
                    if (![url.pathExtension isEqualToString:@"app"]) continue;
                    NSBundle *bundle = [NSBundle bundleWithURL:url];
                    NSString *exe = bundle.executablePath;
                    if (!exe || apps[exe]) continue;
                    NSMutableDictionary *value = [identity(bundle, exe, [bundle objectForInfoDictionaryKey:@"CFBundleDisplayName"] ?: url.lastPathComponent.stringByDeletingPathExtension) mutableCopy];
                    value[@"running"] = @NO; value[@"installed"] = @YES; apps[exe] = value;
                }
            }
        }
        return json(apps.allValues);
    }
}
int clipmo_dark(void) {
    @autoreleasepool { return [[NSUserDefaults.standardUserDefaults stringForKey:@"AppleInterfaceStyle"] isEqualToString:@"Dark"]; }
}
