// Exercises the production bridge against an isolated pasteboard, never the user's clipboard.
#import <AppKit/AppKit.h>
#include <assert.h>
extern char *clipmo_read(const char *);
extern int clipmo_write(const char *, const char *);
extern int64_t clipmo_change_count(const char *);
extern void clipmo_free(char *);
extern int clipmo_paste(int);

static NSDictionary *readBoard(NSPasteboard *pb) {
    char *value = clipmo_read(pb.name.UTF8String);
    assert(value);
    NSData *data = [NSData dataWithBytes:value length:strlen(value)];
    NSDictionary *result = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
    clipmo_free(value);
    return result;
}
int main(void) {
    @autoreleasepool {
        NSPasteboard *pb = [NSPasteboard pasteboardWithUniqueName];
        const char *name = pb.name.UTF8String;
        NSInteger before = clipmo_change_count(name);
        [pb clearContents];
        [pb setString:@"Hello 🌍" forType:NSPasteboardTypeString];
        [pb setString:@"<b>Hello 🌍</b>" forType:NSPasteboardTypeHTML];
        assert(clipmo_change_count(name) != before);
        NSDictionary *value = readBoard(pb);
        assert([value[@"text"] isEqualToString:@"Hello 🌍"]);
        assert([value[@"html"] isEqualToString:@"<b>Hello 🌍</b>"]);
        for (NSString *type in @[@"org.nspasteboard.ConcealedType", @"org.nspasteboard.TransientType", @"org.nspasteboard.AutoGeneratedType", @"com.agilebits.onepassword"]) {
            [pb clearContents];
            [pb setString:@"secret" forType:NSPasteboardTypeString];
            [pb setString:@"" forType:type];
            assert(clipmo_read(name) == NULL);
        }
        [pb clearContents];
        [pb writeObjects:@[[NSURL fileURLWithPath:@"/tmp/Clipmo space 🌍.txt"], [NSURL fileURLWithPath:@"/tmp/second.txt"]]];
        value = readBoard(pb);
        assert([value[@"files"] count] == 2);
        assert([value[@"files"][0] isEqualToString:@"/tmp/Clipmo space 🌍.txt"]);
        NSBitmapImageRep *image = [[NSBitmapImageRep alloc] initWithBitmapDataPlanes:NULL pixelsWide:2 pixelsHigh:2 bitsPerSample:8 samplesPerPixel:4 hasAlpha:YES isPlanar:NO colorSpaceName:NSDeviceRGBColorSpace bytesPerRow:0 bitsPerPixel:0];
        memset(image.bitmapData, 255, image.bytesPerRow * image.pixelsHigh);
        NSData *png = [image representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
        [pb clearContents];
        [pb setData:png forType:NSPasteboardTypePNG];
        assert([readBoard(pb)[@"image"] isEqualToString:[png base64EncodedStringWithOptions:0]]);
        [pb clearContents];
        [pb setData:image.TIFFRepresentation forType:NSPasteboardTypeTIFF];
        assert(readBoard(pb)[@"image"] != nil);
        assert(clipmo_write(name, "{\"text\":\"restored\",\"html\":\"<b>restored</b>\",\"rtf\":\"{\\\\rtf1 restored}\"}"));
        assert([[pb stringForType:NSPasteboardTypeString] isEqualToString:@"restored"]);
        assert([pb dataForType:NSPasteboardTypeRTF] != nil);
        assert(clipmo_read(name) == NULL); // Internal writes must not be recaptured.
        assert(clipmo_write(name, "{\"files\":[\"/tmp/one file.txt\",\"/tmp/two.txt\"]}"));
        assert([[pb readObjectsForClasses:@[NSURL.class] options:@{NSPasteboardURLReadingFileURLsOnlyKey: @YES}] count] == 2);
        assert(clipmo_read(name) == NULL);
        assert(!clipmo_paste(0));
        assert(!clipmo_paste(getpid()));
        [pb releaseGlobally];
        puts("PASS: native text, HTML, RTF, PNG/TIFF, Finder files, opt-outs, internal-write suppression, invalid paste targets");
    }
}
